[project]
name = "PinBot"
version = "1.203.b"
requires-python = ">=3.12"
dependencies = [
    "nonebot>=1.9.1",
    "nonebot-adapter-onebot>=2.4.6",
    "nonebot-plugin-alconna>=0.60.3",
    "nonebot-plugin-apscheduler>=0.5.0",
]
